# Apply to all files without committing:
#   pre-commit run --all-files
# Update this file:
#   pre-commit autoupdate --freeze

# Set the default language versions for the hooks
default_language_version:
  python: python3  # Force all Python hooks to use Python 3
  node: 22.12.0  # Force all Node hooks to use Node 22.12.0

# https://pre-commit.ci/
ci:
  autofix_commit_msg: |
    [pre-commit.ci] auto fixes from pre-commit.com hooks

    for more information, see https://pre-commit.ci
  autofix_prs: false
  autoupdate_branch: 'master'
  autoupdate_commit_msg: '[pre-commit.ci] pre-commit autoupdate'
  autoupdate_schedule: monthly
  submodules: false

# Globally exclude files
# https://pre-commit.com/#top_level-exclude
exclude: |
  (?x)(
    LICENSE|
    .idea/|
    wp-content/|
    _pastebin_/wp-test-data/|
    ISSUE_TEMPLATE/
  )

# pre-commit setup
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: cef0300fd0fc4d2a87a85fa2093c6b283ea36f4b  # frozen: v5.0.0
    hooks:
      # Identify invalid files
      - id: check-yaml
        name: Check YAML
        description: This hook checks that your YAML is parseable.

      - id: check-json
        name: Check JSON
        description: This hook checks that your JSON is parseable.

      - id: check-xml
        name: Check XML
        description: This hook checks that your XML is parseable.

      # git checks
      - id: check-merge-conflict
        name: Check Merge Conflict
        description: This hook checks for files that contain merge conflict strings.

      - id: check-added-large-files
        name: Check Added Large Files
        description: This hook checks for large files that have been added to the repository.
        args:
          - --maxkb=1000

      - id: detect-private-key
        name: Detect Private Key
        description: This hook detects private keys.

      - id: check-case-conflict
        name: Check Case Conflict
        description: This hook checks for files with names that differ only in case.

      # General quality checks
      - id: mixed-line-ending
        name: Mixed Line Ending
        description: This hook checks for files that have mixed line endings.
        args:
          - --fix=lf

      - id: trailing-whitespace
        name: Trailing Whitespace
        description: This hook removes trailing whitespace.
        args:
          - --markdown-linebreak-ext=md

      - id: check-executables-have-shebangs
        name: Check Executables Have Shebangs
        description: This hook checks that all executable files have a shebang.

      - id: end-of-file-fixer
        name: End of File Fixer
        description: This hook ensures that files end with a newline.

  - repo: https://github.com/editorconfig-checker/editorconfig-checker.python
    rev: 1a92c0953500d402fc49ceb67ad7fbf7cabad38a  # frozen: 3.0.3
    hooks:
      - id: editorconfig-checker
        name: EditorConfig Checker
        description: This hook checks for compliance with definitions made in EditorConfig files.

  - repo: https://github.com/executablebooks/mdformat
    rev: e20b1ac5acb8aba0b49d3a9109c6e6b58684ee83  # frozen: 0.7.21
    hooks:
      - id: mdformat
        name: Mdformat
        description: This hook checks for Markdown formatting issues.
        additional_dependencies:  # https://mdformat.readthedocs.io/en/stable/users/plugins.html#code-formatter-plugins
          - mdformat-gfm==0.4.1  # Mdformat plugin for GitHub Flavored Markdown compatibility » https://github.com/hukkin/mdformat-gfm/tags
          - mdformat-toc==0.3.0  # Mdformat plugin to generate a table of contents » https://github.com/hukkin/mdformat-toc/tags
          - mdformat-shfmt==0.2.0  # Mdformat plugin to format shell code blocks » https://github.com/hukkin/mdformat-shfmt/tags

  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: cb3c2be894b151dff143b1baf6acbd55f2b7faed  # frozen: 0.30.0
    hooks:
      - id: check-github-actions
        name: Check GitHub Actions
        description: This hook checks that GitHub Actions files are valid.
        args:
          - --verbose

      - id: check-github-workflows
        name: Check GitHub Workflows
        description: This hook checks that GitHub Workflows files are valid.
        args:
          - --verbose

      - id: check-dependabot
        name: Check Dependabot Configuration
        description: This hook checks that Dependabot configuration files are valid.
        args:
          - --verbose
